import { ElementType, LevelConfig } from '../types/game';

export const ELEMENT_TYPES: ElementType[] = ['cat', 'dog', 'rabbit', 'bear', 'panda'];

export const LEVEL_CONFIGS: LevelConfig[] = [
  { id: 1, targets: [{ type: 'cat', count: 10 }], moves: 20 },
  { id: 2, targets: [{ type: 'dog', count: 10 }], moves: 20 },
  { id: 3, targets: [{ type: 'rabbit', count: 10 }], moves: 20 },
  { id: 4, targets: [{ type: 'bear', count: 10 }], moves: 20 },
  { id: 5, targets: [{ type: 'panda', count: 10 }], moves: 20 },
  { id: 6, targets: [{ type: 'cat', count: 15 }, { type: 'dog', count: 10 }], moves: 25 },
  { id: 7, targets: [{ type: 'rabbit', count: 15 }, { type: 'bear', count: 10 }], moves: 25 },
  { id: 8, targets: [{ type: 'panda', count: 15 }, { type: 'cat', count: 10 }], moves: 25 },
  { id: 9, targets: [{ type: 'dog', count: 15 }, { type: 'rabbit', count: 10 }], moves: 25 },
  { id: 10, targets: [{ type: 'bear', count: 20 }, { type: 'panda', count: 15 }], moves: 30 },
  { id: 11, targets: [{ type: 'cat', count: 20 }, { type: 'dog', count: 15 }], moves: 30 },
  { id: 12, targets: [{ type: 'rabbit', count: 20 }, { type: 'bear', count: 15 }], moves: 30 },
  { id: 13, targets: [{ type: 'panda', count: 20 }, { type: 'cat', count: 15 }], moves: 30 },
  { id: 14, targets: [{ type: 'dog', count: 20 }, { type: 'rabbit', count: 15 }], moves: 30 },
  { id: 15, targets: [{ type: 'bear', count: 25 }, { type: 'panda', count: 20 }], moves: 35 },
  { id: 16, targets: [{ type: 'cat', count: 25 }, { type: 'dog', count: 20 }], moves: 35 },
  { id: 17, targets: [{ type: 'rabbit', count: 25 }, { type: 'bear', count: 20 }], moves: 35 },
  { id: 18, targets: [{ type: 'panda', count: 25 }, { type: 'cat', count: 20 }], moves: 35 },
  { id: 19, targets: [{ type: 'dog', count: 25 }, { type: 'rabbit', count: 20 }], moves: 35 },
  { id: 20, targets: [{ type: 'bear', count: 30 }, { type: 'panda', count: 25 }], moves: 40 },
  { id: 21, targets: [{ type: 'cat', count: 30 }, { type: 'dog', count: 25 }], moves: 40 },
  { id: 22, targets: [{ type: 'rabbit', count: 30 }, { type: 'bear', count: 25 }], moves: 40 },
  { id: 23, targets: [{ type: 'panda', count: 30 }, { type: 'cat', count: 25 }], moves: 40 },
  { id: 24, targets: [{ type: 'dog', count: 30 }, { type: 'rabbit', count: 25 }], moves: 40 },
  { id: 25, targets: [{ type: 'bear', count: 35 }, { type: 'panda', count: 30 }], moves: 45 },
  { id: 26, targets: [{ type: 'cat', count: 35 }, { type: 'dog', count: 30 }], moves: 45 },
  { id: 27, targets: [{ type: 'rabbit', count: 35 }, { type: 'bear', count: 30 }], moves: 45 },
  { id: 28, targets: [{ type: 'panda', count: 35 }, { type: 'cat', count: 30 }], moves: 45 },
  { id: 29, targets: [{ type: 'dog', count: 35 }, { type: 'rabbit', count: 30 }], moves: 45 },
  { id: 30, targets: [{ type: 'bear', count: 40 }, { type: 'panda', count: 35 }], moves: 50 },
  { id: 31, targets: [{ type: 'cat', count: 40 }, { type: 'dog', count: 35 }], moves: 50 },
  { id: 32, targets: [{ type: 'rabbit', count: 40 }, { type: 'bear', count: 35 }], moves: 50 },
  { id: 33, targets: [{ type: 'panda', count: 40 }, { type: 'cat', count: 35 }], moves: 50 },
  { id: 34, targets: [{ type: 'dog', count: 40 }, { type: 'rabbit', count: 35 }], moves: 50 },
  { id: 35, targets: [{ type: 'bear', count: 45 }, { type: 'panda', count: 40 }], moves: 55 },
  { id: 36, targets: [{ type: 'cat', count: 45 }, { type: 'dog', count: 40 }], moves: 55 },
  { id: 37, targets: [{ type: 'rabbit', count: 45 }, { type: 'bear', count: 40 }], moves: 55 },
  { id: 38, targets: [{ type: 'panda', count: 45 }, { type: 'cat', count: 40 }], moves: 55 },
  { id: 39, targets: [{ type: 'dog', count: 45 }, { type: 'rabbit', count: 40 }], moves: 55 },
  { id: 40, targets: [{ type: 'bear', count: 50 }, { type: 'panda', count: 45 }], moves: 60 },
  { id: 41, targets: [{ type: 'cat', count: 50 }, { type: 'dog', count: 45 }], moves: 60 },
  { id: 42, targets: [{ type: 'rabbit', count: 50 }, { type: 'bear', count: 45 }], moves: 60 },
  { id: 43, targets: [{ type: 'panda', count: 50 }, { type: 'cat', count: 45 }], moves: 60 },
  { id: 44, targets: [{ type: 'dog', count: 50 }, { type: 'rabbit', count: 45 }], moves: 60 },
  { id: 45, targets: [{ type: 'bear', count: 55 }, { type: 'panda', count: 50 }], moves: 65 },
  { id: 46, targets: [{ type: 'cat', count: 55 }, { type: 'dog', count: 50 }], moves: 65 },
  { id: 47, targets: [{ type: 'rabbit', count: 55 }, { type: 'bear', count: 50 }], moves: 65 },
  { id: 48, targets: [{ type: 'panda', count: 55 }, { type: 'cat', count: 50 }], moves: 65 },
  { id: 49, targets: [{ type: 'dog', count: 55 }, { type: 'rabbit', count: 50 }], moves: 65 },
  { id: 50, targets: [{ type: 'bear', count: 60 }, { type: 'panda', count: 55 }], moves: 70 },
];

export function getLevelConfig(level: number): LevelConfig {
  return LEVEL_CONFIGS[level - 1] || LEVEL_CONFIGS[0];
}
